name: nginx_le_container
version: 6.2.5
description: Commands that live in the nginx-le docker container.
repository: https://github.com/bsutton/nginx-le
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  async: ^2.4.2
  args: ^2.0.0
  path: ^1.6.4
  cron: ^0.3.0
  dcli: ^1.0.0
  xml: ^5.0.2
  http: ^0.13.0
  intl: ^0.17.0
  isolates: ^3.0.0
  meta: ^1.0.0
  pedantic: ^1.0.0
  public_suffix: ^3.0.0
  uuid: ^3.0.1
  nginx_le_shared: ^6.0.0
dev_dependencies: 
  mocktail: ^0.1.1
  test: ^1.0.0
  settings_yaml: ^3.0.1
dependency_overrides: 
  nginx_le_shared: 
    path: ../shared
