name: nginx_le_shared
version: 6.1.0
homepage: https://github.com/bsutton/nginx-le
description: shared library used by Nginx-LE
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  async: ^2.4.2
  args: ^2.0.0
  path: ^1.6.4
  cron: ^0.3.0
  docker2: ^1.0.0
  dcli: ^1.0.0
  instant: ^0.4.1
  http: ^0.13.0
  intl: ^0.17.0
  isolates: ^3.0.3+7
  mailer: ^4.0.0
  meta: ^1.0.0
  pedantic: ^1.0.0
  public_suffix: ^2.0.1
  settings_yaml: ^3.0.1
  uuid: ^3.0.1
  xml: ^5.0.2
  yaml: ^3.1.0
dev_dependencies: 
  test: ^1.0.0
